version: '3.3'
services: 
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes: 
      - ~/my_data/mongo:/data/db
    networks:
      - default
  auth-server:
    build: ./authentication-server/
    depends_on:
      - mongodb
    ports: 
      - "3001:3001"
    networks:
      - default
    env_file:
      - .env
  resource-server:
    build: ./resource-server/
    ports: 
      - "4000:4000"
    networks:
      - default
    env_file:
      - .env
  
volumes: 
  my_data:
networks:
  default: